import { defineConfig, coverageConfigDefaults } from 'vitest/config';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { resolve } from 'path';

export default defineConfig({
  plugins: [svelte()],
  test: {
    environment: 'happy-dom',
    // The locale is global and some files move it; this gives every file the same starting
    // point. Fourteen assertions depended on worker order until 2026-09-17 - see the file.
    setupFiles: ['./src/test/locale.ts'],
    globals: true,
    include: ['src/**/*.{test,spec}.ts'],
    coverage: {
      exclude: [
        ...coverageConfigDefaults.exclude,
        // One generated getter per message key (2669 files) - no logic of its own to cover, and
        // every one of them is instrumented just for being imported transitively by `m.xxx()`.
        'src/lib/paraglide/**',
        // Generated by protobufjs/wasm-bindgen, never hand-edited - `codec.ts` (hand-written,
        // its own coverage) is what actually wraps these and stays instrumented.
        'src/lib/proto/canari.js',
        'src/lib/proto/canari.d.ts',
        'src/lib/wasm/**',
        // Test infrastructure (shared mocks, helpers), not application code.
        'src/test/**',
      ],
    },
  },
  resolve: {
    // THE CLIENT BUILD OF SVELTE, NOT THE SERVER ONE. Without it `svelte` resolves to
    // `index-server.js`, whose `mount()` throws `lifecycle_function_unavailable` - so a component
    // could only ever be tested through the functions it happens to export, and a defect that lives
    // in the DOM event path (see `Modal.dismissal.svelte.test.ts`) has nowhere to be caught. Measured
    // 2026-09-05: the 257 files and 2449 tests that predate this answer identically with it.
    conditions: ['browser'],
    alias: {
      '$app/navigation': resolve(import.meta.dirname, './src/test/mocks/app-navigation.ts'),
      $lib: resolve(import.meta.dirname, './src/lib'),
      $app: resolve(import.meta.dirname, './node_modules/@sveltejs/kit/src/runtime/app'),
    },
  },
});
