import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * The hardware Back press has an OWNER, and this is what says so.
 *
 * `WryActivity` registers an `OnBackPressedCallback` that asks the WebView `canGoBack()` and calls
 * `goBack()`; `TauriActivity` turns it off with `handleBackNavigation = false`. With that off,
 * nothing in this app handles the press: the system's predictive-back dispatcher hands it to
 * whoever registered, and on `targetSdk 36` the only candidate is the callback Chromium's WebView
 * installs for its own history - on its own schedule, which is not a contract.
 *
 * MEASURED ON A Mi 9T 2026-09-21, three runs of the same build with `history.length 3` read through
 * CDP at the moment of the press: one stepped conversation -> list -> posts -> exit, the others
 * exited on the FIRST press, at 3 s, 8 s and 20 s after the landing alike. `MainActivity` overrides
 * the flag back to `true` so the press is decided here instead.
 *
 * Nothing about this is visible at compile time, and `gen/android` is regenerated by
 * `tauri android init` and by a major Tauri upgrade - the same trap `androidFcmManifest.test.ts`
 * exists for.
 */
const here = dirname(fileURLToPath(import.meta.url));
const ANDROID_JAVA = resolve(
  here,
  '../../../src-tauri/gen/android/app/src/main/java/fr/emse/canari'
);

const mainActivity = readFileSync(resolve(ANDROID_JAVA, 'MainActivity.kt'), 'utf8');
const wryActivity = readFileSync(resolve(ANDROID_JAVA, 'generated/WryActivity.kt'), 'utf8');

describe('the Android Back press is handled by this app, not by luck', () => {
  it('MainActivity claims the press back from the system', () => {
    expect(mainActivity).toMatch(/override\s+val\s+handleBackNavigation\s*:\s*Boolean\s*=\s*true/);
  });

  it('and the flag still BUYS the WebView history walk it is claimed for', () => {
    // If a Tauri upgrade ever rewrites this callback, `= true` stops meaning what the override says
    // it means, and the phone is the only place that would notice. Fail here instead.
    expect(wryActivity).toContain('if (handleBackNavigation)');
    expect(wryActivity).toMatch(/canGoBack\(\)[\s\S]{0,120}goBack\(\)/);
  });
});
