<script lang="ts">
  import { Plus, Trash2, Users } from '@lucide/svelte';
  import CheckboxGroup from '$lib/components/ui/CheckboxGroup.svelte';
  import Select from '$lib/components/ui/Select.svelte';
  import Toggle from '$lib/components/ui/Toggle.svelte';
  import { CONTROL_HINT_CLASS, controlClass } from '$lib/components/ui/controlClasses';
  import type { MembershipTier } from '$lib/associations/api';
  import type { FormItem } from '$lib/forms/api';
  import type { Bucket, Dimension } from '$lib/pricing/priceMatrix';
  import PromoPicker from './PromoPicker.svelte';
  import type { FormationOption } from '$lib/pricing/criteriaOptions';
  import { m } from '$lib/paraglide/messages';

  /**
   * One criterion of the pricing grid: its groups, and what each group captures.
   *
   * A criterion is a PARTITION, not a filter - which is why "Tous les autres" is drawn here, at the
   * end, greyed and undeletable. It is generated by the server and cannot be edited, and showing it
   * is what makes the grid legible: a manager can see that everybody has a price without counting.
   */
  interface Props {
    dimension: Dimension;
    /** Cotisation tiers of the beneficiary association, by NAME. */
    tiers: MembershipTier[];
    /** Formation values in use, with counts. */
    formations: FormationOption[];
    /** The form's questions, for an `answer` criterion. */
    items: FormItem[];
    onAddBucket: (bucket: Bucket) => void;
    onRemoveBucket: (bucketId: string) => void;
    onRemove: () => void;
    onChange: () => void;
  }

  let {
    dimension,
    tiers,
    formations,
    items,
    onAddBucket,
    onRemoveBucket,
    onRemove,
    onChange,
  }: Props = $props();

  const title = $derived(
    dimension.kind === 'cotisation'
      ? m.form_criterion_cotisation()
      : dimension.kind === 'promo'
        ? m.form_criterion_promo()
        : dimension.kind === 'formation'
          ? m.form_criterion_formation()
          : m.form_criterion_answer()
  );

  /** Only questions offering options can divide anybody. */
  const questionOptions = $derived(
    items
      .filter((i) => (i.options?.length ?? 0) > 0)
      .map((i) => ({ value: i.id, label: i.label || m.form_criterion_untitled_question() }))
  );

  const chosenQuestion = $derived(items.find((i) => i.id === dimension.questionId) ?? null);

  /** Formation values and option ids, the two criteria a checkbox list drives. */
  function valuesAsStrings(bucket: Bucket): string[] {
    return (bucket.values ?? []).map(String);
  }

  function setValues(bucket: Bucket, next: string[]) {
    bucket.values = next;
    onChange();
  }

  /** `null` is the base tier, which has no key - carried through the checkbox list as an empty string. */
  const TIER_BASE = '';

  function tierKeysAsStrings(bucket: Bucket): string[] {
    return (bucket.variantKeys ?? []).map((k) => k ?? TIER_BASE);
  }

  function setTierKeys(bucket: Bucket, next: string[]) {
    bucket.variantKeys = next.map((k) => (k === TIER_BASE ? null : k));
    onChange();
  }

  function addGroup() {
    onAddBucket({
      id: `b${Math.random().toString(36).slice(2, 8)}`,
      label: '',
      ...(dimension.kind === 'cotisation' ? { anyTier: true } : { values: [] }),
    });
  }
</script>

<div class="border-cn-border/70 bg-cn-bg/30 space-y-4 rounded-2xl border-2 p-4">
  <div class="flex items-start justify-between gap-3">
    <div>
      <p class="text-text-main text-sm font-bold">{title}</p>
      {#if dimension.kind === 'answer'}
        <p class={CONTROL_HINT_CLASS}>{m.form_criterion_answer_hint()}</p>
      {/if}
    </div>
    <button
      type="button"
      onclick={onRemove}
      class="border-red-err/30 bg-red-err/10 text-red-err hover:bg-red-err/20 inline-flex shrink-0 items-center gap-1.5 rounded-xl border-2 px-3 py-1.5 text-xs font-bold transition-colors"
    >
      <Trash2 size={13} />
      {m.form_criterion_remove()}
    </button>
  </div>

  {#if dimension.kind === 'answer'}
    <Select
      label={m.form_criterion_question_label()}
      value={dimension.questionId ?? ''}
      options={[{ value: '', label: m.form_criterion_question_placeholder() }, ...questionOptions]}
      onValueChange={(v) => {
        dimension.questionId = v || undefined;
        // The options of the previous question mean nothing under the new one.
        for (const b of dimension.buckets) b.values = [];
        onChange();
      }}
    />
  {/if}

  <div class="space-y-3">
    {#each dimension.buckets as bucket (bucket.id)}
      <div class="border-cn-border/60 space-y-3 rounded-xl border bg-(--cn-surface) p-3">
        <div class="flex items-center gap-2">
          <input
            bind:value={bucket.label}
            oninput={onChange}
            placeholder={m.form_criterion_group_name_placeholder()}
            class="{controlClass(!bucket.label.trim(), 'compact')} flex-1"
          />
          <button
            type="button"
            onclick={() => onRemoveBucket(bucket.id)}
            class="text-text-muted hover:bg-red-err/10 shrink-0 rounded-lg p-2 transition-colors hover:text-red-600"
            title={m.form_criterion_group_remove()}
          >
            <Trash2 size={14} />
          </button>
        </div>

        {#if dimension.kind === 'cotisation'}
          <Toggle
            label={m.form_criterion_any_tier()}
            bind:checked={
              () => bucket.anyTier ?? false,
              (v) => {
                bucket.anyTier = v;
                if (v) bucket.variantKeys = [];
                onChange();
              }
            }
          />
          {#if !bucket.anyTier}
            <CheckboxGroup
              options={tiers.map((t) => ({ value: t.variantKey ?? TIER_BASE, label: t.name }))}
              bind:selected={() => tierKeysAsStrings(bucket), (v) => setTierKeys(bucket, v)}
              emptyLabel={m.form_criterion_no_tiers()}
            />
          {/if}
        {:else if dimension.kind === 'promo'}
          <PromoPicker
            selected={(bucket.values ?? []) as number[]}
            onChange={(next) => {
              bucket.values = next;
              onChange();
            }}
          />
        {:else if dimension.kind === 'formation'}
          <CheckboxGroup
            options={formations.map((f) => ({
              value: f.value,
              label: f.value,
              hint: m.form_criterion_formation_count({ count: f.count }),
            }))}
            bind:selected={() => valuesAsStrings(bucket), (v) => setValues(bucket, v)}
            emptyLabel={m.form_criterion_no_formations()}
          />
        {:else}
          <CheckboxGroup
            options={(chosenQuestion?.options ?? []).map((o) => ({
              value: o.id ?? '',
              label: o.label,
            }))}
            bind:selected={() => valuesAsStrings(bucket), (v) => setValues(bucket, v)}
            emptyLabel={m.form_criterion_no_options()}
          />
        {/if}
      </div>
    {/each}

    <!-- Generated by the server, shown because it is what makes the grid a partition: everybody who
         is in none of the groups above is in this one, and therefore has a price. -->
    <div
      class="border-cn-border/50 text-text-muted flex items-center gap-2 rounded-xl border border-dashed px-3 py-2.5 text-sm"
    >
      <Users size={14} class="shrink-0" />
      <span class="font-semibold">{m.form_criterion_others()}</span>
      <span class="text-xs">{m.form_criterion_others_hint()}</span>
    </div>

    <button
      type="button"
      onclick={addGroup}
      class="border-cn-border text-text-main hover:border-cn-yellow/40 inline-flex items-center gap-1.5 rounded-xl border-2 px-3 py-2 text-xs font-bold transition-colors"
    >
      <Plus size={13} />
      {m.form_criterion_add_group()}
    </button>
  </div>
</div>
