export const CHANNEL_PERMISSIONS = {
  CHANNEL_READ: 'channel.read',
  CHANNEL_WRITE: 'channel.write',
  CHANNEL_MANAGE: 'channel.manage',
  MEMBER_INVITE: 'member.invite',
  MEMBER_KICK: 'member.kick',
  ROLE_MANAGE: 'role.manage',
} as const;

export type ChannelPermission =
  (typeof CHANNEL_PERMISSIONS)[keyof typeof CHANNEL_PERMISSIONS];

export const DEFAULT_OWNER_PERMISSIONS: ChannelPermission[] = [
  CHANNEL_PERMISSIONS.CHANNEL_READ,
  CHANNEL_PERMISSIONS.CHANNEL_WRITE,
  CHANNEL_PERMISSIONS.CHANNEL_MANAGE,
  CHANNEL_PERMISSIONS.MEMBER_INVITE,
  CHANNEL_PERMISSIONS.MEMBER_KICK,
  CHANNEL_PERMISSIONS.ROLE_MANAGE,
];

export const DEFAULT_MEMBER_PERMISSIONS: ChannelPermission[] = [
  CHANNEL_PERMISSIONS.CHANNEL_READ,
  CHANNEL_PERMISSIONS.CHANNEL_WRITE,
];
