/**
 * Renders a legacy cotisation load as ONE idempotent SQL transaction, for estates the import script
 * cannot connect to.
 *
 * WHY THIS EXISTS. Neither database container publishes a port, and the sanctioned way into either
 * estate is `docker exec ... psql` from the box itself
 * (`docs/wiki/infrastructure/databases.md`). The alternative - lifting the production password onto
 * a workstation to open a tunnel - buys nothing and puts a credential somewhere it has no reason to
 * be. Emitting text costs nothing, keeps the source files (which name ~5600 real people) on the
 * machine that already holds them, and leaves a transaction a human can read before applying it.
 *
 * IT CARRIES ITS OWN PRECONDITIONS, and that is the whole point of the `DO` block below. The
 * connected path asks three questions before writing a single row - does the association exist, is
 * cotisation enabled on it, does the named tier exist in its catalogue - and an emitted file that
 * skipped them would be the same load with its guards removed. The third one matters most: the tier
 * is validated again by `grantCotisant` at every claim, so a load naming a tier that does not exist
 * produces no error here and a refusal per member, months apart, with nothing watching.
 *
 * THE ASSOCIATION ID IS RESOLVED BY THE STATEMENT, NEVER INTERPOLATED. Both estates run the same
 * schema with different ids, so a file carrying one estate's uuid would apply cleanly against the
 * other and attach every row to the wrong association. Joining on `slug` makes the same file correct
 * on any estate and wrong on none.
 */

/** One cotisant, already parsed, keyed and checked for ambiguity by the caller. */
export interface LegacyCotisationRow {
  matchKey: string;
  sourceLabel: string;
  metadata: Record<string, unknown>;
}

/**
 * Quotes a string as a PostgreSQL literal. `standard_conforming_strings` is on by default, so a
 * backslash is an ordinary character and doubling the apostrophe is the whole of the escaping.
 */
function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** The same, for a value whose absence is meaningful - `variantKey` NULL is the base tier. */
function sqlNullableString(value: string | null): string {
  return value === null ? 'NULL' : sqlString(value);
}

/**
 * @param rows - the cotisants to stage; an empty list renders the preconditions and nothing else,
 *   which is a valid transaction that writes nothing rather than a syntax error.
 * @param slug - the association the rows belong to, resolved to an id by the statement itself.
 * @param variantKey - the tier to grant, `null` for the base tier (the BDE has one; Le Cercle
 *   dropped its own, so its rows must name `avec-alcool`).
 * @param batch - which load put these rows here, recorded per row.
 */
export function renderLegacyCotisationSql(args: {
  rows: LegacyCotisationRow[];
  slug: string;
  variantKey: string | null;
  batch: string;
}): string {
  const { rows, slug, variantKey, batch } = args;
  const tierLabel = variantKey === null ? 'base' : variantKey;

  const header = `-- ${rows.length} legacy cotisant(s) for "${slug}", tier ${tierLabel}, batch "${batch}".
-- Generated by scripts/import-legacy-cotisations.ts --emit-sql.
--
-- THIS FILE NAMES REAL PEOPLE. It must never be committed, and the repository is public.
--
-- Idempotent: a row already PENDING for the same person and association is left untouched, and a
-- row already CLAIMED is never reopened - the unique index this relies on is partial, so a claimed
-- row does not block a later deliberate re-load.

BEGIN;

DO $$
DECLARE
  assoc_id uuid;
  assoc_mode text;
BEGIN
  SELECT id, "cotisationMode" INTO assoc_id, assoc_mode
    FROM associations WHERE slug = ${sqlString(slug)};

  IF assoc_id IS NULL THEN
    RAISE EXCEPTION 'no association with slug %', ${sqlString(slug)};
  END IF;

  IF assoc_mode IS NULL THEN
    RAISE EXCEPTION 'cotisation is not enabled on %', ${sqlString(slug)};
  END IF;

  -- Asked HERE rather than left to the claim. grantCotisant validates the tier against this same
  -- catalogue, so a load naming a tier that does not exist stages perfectly and then refuses every
  -- member one at a time, at whatever hour each of them happens to sign in.
  IF NOT EXISTS (
    SELECT 1 FROM association_products
     WHERE "associationId" = assoc_id
       AND type = 'membership'
       AND "variantKey" IS NOT DISTINCT FROM ${sqlNullableString(variantKey)}::varchar
  ) THEN
    RAISE EXCEPTION '% has no % tier', ${sqlString(slug)}, ${sqlString(tierLabel)};
  END IF;
END $$;
`;

  if (rows.length === 0) return `${header}\nCOMMIT;\n`;

  const values = rows
    .map(
      (r) =>
        `  (${sqlString(r.matchKey)}, ${sqlString(r.sourceLabel)}, ${sqlString(JSON.stringify(r.metadata))})`
    )
    .join(',\n');

  return `${header}
INSERT INTO legacy_cotisations
  ("matchKey", "sourceLabel", "associationId", "variantKey", "sourceBatch", metadata)
SELECT v."matchKey", v."sourceLabel", a.id,
       ${sqlNullableString(variantKey)}, ${sqlString(batch)}, v.metadata::jsonb
  FROM (VALUES
${values}
  ) AS v("matchKey", "sourceLabel", metadata)
  CROSS JOIN associations a
 WHERE a.slug = ${sqlString(slug)}
    ON CONFLICT ("matchKey", "associationId") WHERE "claimedByUserId" IS NULL DO NOTHING;

COMMIT;
`;
}
