// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageSentEvent = { id: string, senderId: string, username: string, content: string, timestamp: string, conversationId: string | null, };
