FROM node:20-alpine AS builder

WORKDIR /app

COPY apps/auth-service/package*.json ./
RUN npm install --legacy-peer-deps

COPY apps/auth-service ./
RUN npx tsc -p tsconfig.build.json

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/package*.json ./
RUN npm install --omit=dev --legacy-peer-deps

COPY --from=builder /app/dist ./dist

EXPOSE 3002

CMD ["node", "dist/main"]
