import { readFileSync } from 'node:fs';
import sharp from 'sharp';
import { LOGO_BIRD_FILL, SVG } from '../scripts/logo-render.mjs';

/**
 * The icons are BINARY and generated by `scripts/gen-web-icons.mjs`, so nothing in
 * a review shows what they contain - and the vector they all come from is a single
 * path, which a review reads no better. These assertions pin the properties that
 * are invisible in a diff and that only fail on a device: an icon declared but not
 * shipped, a home-screen icon with an alpha channel, and a logo drawn flush
 * against its own canvas edge.
 */

const APP_HTML = readFileSync('src/app.html', 'utf8');

/** Every icon `href` declared in `app.html`, as a path under `static/`. */
function declaredIconPaths(): string[] {
  const links = APP_HTML.match(/<link[^>]*rel="(?:apple-touch-)?icon"[^>]*>/g) ?? [];
  return links.map((tag) => {
    const href = tag.match(/href="([^"]+)"/)?.[1];
    if (!href) throw new Error(`icon link with no href: ${tag}`);
    return `static/${href.replace('%sveltekit.assets%/', '')}`;
  });
}

describe('the icons app.html declares', () => {
  it('declares the apple-touch-icon, which is what stops Safari probing for it', () => {
    // Three 404s on production came from NOT declaring it: Safari falls back to
    // /apple-touch-icon.png and /apple-touch-icon-precomposed.png on its own, and an
    // "add to home screen" that finds neither gets a screenshot of the page instead.
    expect(APP_HTML).toContain('rel="apple-touch-icon"');
  });

  it('ships every file it declares', () => {
    const paths = declaredIconPaths();
    expect(paths.length).toBeGreaterThanOrEqual(3);
    for (const p of paths) expect(() => readFileSync(p)).not.toThrow();
  });

  it('ships favicon.ico, which nothing declares and everything asks for', () => {
    expect(() => readFileSync('static/favicon.ico')).not.toThrow();
  });
});

describe('static/apple-touch-icon.png', () => {
  it('is 180x180, the size every current iOS device asks for', async () => {
    const { width, height } = await sharp('static/apple-touch-icon.png').metadata();
    expect({ width, height }).toEqual({ width: 180, height: 180 });
  });

  it('is fully OPAQUE, because iOS composites a transparent icon onto black', async () => {
    // The failure this pins is not a crash: the icon renders, as a black square with a
    // yellow bird on it, on the one surface nobody looks at after a deploy.
    const { isOpaque } = await sharp('static/apple-touch-icon.png').stats();
    expect(isOpaque).toBe(true);
  });
});

describe('static/favicon.ico', () => {
  const ico = readFileSync('static/favicon.ico');
  const HEADER_BYTES = 6;
  const ENTRY_BYTES = 16;

  it('is an icon container carrying several sizes, not one image renamed', () => {
    expect(ico.readUInt16LE(0)).toBe(0); // reserved
    expect(ico.readUInt16LE(2)).toBe(1); // 1 = icon, 2 would be a cursor
    expect(ico.readUInt16LE(4)).toBeGreaterThan(1);
  });

  it('points every directory entry at a payload that is inside the file', () => {
    // A packer that miscomputes one offset produces a file that opens in some readers
    // and not others, which is indistinguishable from "the browser cached the old one".
    const count = ico.readUInt16LE(4);
    for (let n = 0; n < count; n++) {
      const entry = HEADER_BYTES + ENTRY_BYTES * n;
      const size = ico.readUInt32LE(entry + 8);
      const offset = ico.readUInt32LE(entry + 12);
      expect(offset).toBeGreaterThanOrEqual(HEADER_BYTES + ENTRY_BYTES * count);
      expect(offset + size).toBeLessThanOrEqual(ico.length);
      expect(ico.readUInt8(entry)).toBeGreaterThan(0); // width, 0 would mean 256
    }
  });
});

describe('static/favicon.svg', () => {
  /**
   * Bird bounding box inside the vector's canvas, in fractions of the canvas.
   *
   * Rendered rather than parsed: the drawing is one path with a transform on it,
   * so the only honest answer to "does it touch the edge" comes from pixels.
   */
  async function birdBox() {
    const png = await sharp(SVG, { density: 720 }).png().toBuffer();
    const canvas = await sharp(png).metadata();
    const { width, height, trimOffsetLeft, trimOffsetTop } = (
      await sharp(png).trim({ threshold: 0 }).toBuffer({ resolveWithObject: true })
    ).info;
    // sharp types the offsets as optional because they only exist after a trim.
    // We just trimmed, so an absence means the render produced nothing to trim -
    // which would make every assertion below pass against a blank canvas.
    if (trimOffsetLeft === undefined || trimOffsetTop === undefined) {
      throw new Error('sharp reported no trim offsets: the vector rendered empty');
    }
    return {
      left: -trimOffsetLeft / canvas.width,
      top: -trimOffsetTop / canvas.height,
      right: (canvas.width + trimOffsetLeft - width) / canvas.width,
      bottom: (canvas.height + trimOffsetTop - height) / canvas.height,
      fill: width / canvas.width,
    };
  }

  it('keeps the bird off its own edge on all four sides', async () => {
    // The defect this pins is not visible in any diff and not visible on any
    // surface that pads the logo itself: it only shows where a consumer masks the
    // whole canvas into a circle - a tab chip, a launcher - and the bird's
    // extremities come out clipped or flush against the border.
    const { left, top, right, bottom } = await birdBox();
    for (const margin of [left, top, right, bottom]) expect(margin).toBeGreaterThan(0.04);
  });

  it('fills the fraction of its canvas the icon generators are told it does', async () => {
    // Both generators size the BIRD and derive the canvas from this factor. Redraw
    // the vector at a different scale without updating it and every launcher icon
    // silently changes size, on the one surface nobody looks at after a deploy.
    const { fill } = await birdBox();
    expect(fill).toBeCloseTo(LOGO_BIRD_FILL, 2);
  });
});
