import { readFileSync } from 'node:fs';
import sharp from 'sharp';

/**
 * The icons are BINARY and generated by `scripts/gen-web-icons.mjs`, so nothing in
 * a review shows what they contain. These assertions pin the two properties that
 * are invisible in a diff and that only fail on a device: an icon declared but not
 * shipped, and a home-screen icon with an alpha channel.
 */

const APP_HTML = readFileSync('src/app.html', 'utf8');

/** Every icon `href` declared in `app.html`, as a path under `static/`. */
function declaredIconPaths(): string[] {
  const links = APP_HTML.match(/<link[^>]*rel="(?:apple-touch-)?icon"[^>]*>/g) ?? [];
  return links.map((tag) => {
    const href = tag.match(/href="([^"]+)"/)?.[1];
    if (!href) throw new Error(`icon link with no href: ${tag}`);
    return `static/${href.replace('%sveltekit.assets%/', '')}`;
  });
}

describe('the icons app.html declares', () => {
  it('declares the apple-touch-icon, which is what stops Safari probing for it', () => {
    // Three 404s on production came from NOT declaring it: Safari falls back to
    // /apple-touch-icon.png and /apple-touch-icon-precomposed.png on its own, and an
    // "add to home screen" that finds neither gets a screenshot of the page instead.
    expect(APP_HTML).toContain('rel="apple-touch-icon"');
  });

  it('ships every file it declares', () => {
    const paths = declaredIconPaths();
    expect(paths.length).toBeGreaterThanOrEqual(3);
    for (const p of paths) expect(() => readFileSync(p)).not.toThrow();
  });

  it('ships favicon.ico, which nothing declares and everything asks for', () => {
    expect(() => readFileSync('static/favicon.ico')).not.toThrow();
  });
});

describe('static/apple-touch-icon.png', () => {
  it('is 180x180, the size every current iOS device asks for', async () => {
    const { width, height } = await sharp('static/apple-touch-icon.png').metadata();
    expect({ width, height }).toEqual({ width: 180, height: 180 });
  });

  it('is fully OPAQUE, because iOS composites a transparent icon onto black', async () => {
    // The failure this pins is not a crash: the icon renders, as a black square with a
    // yellow bird on it, on the one surface nobody looks at after a deploy.
    const { isOpaque } = await sharp('static/apple-touch-icon.png').stats();
    expect(isOpaque).toBe(true);
  });
});

describe('static/favicon.ico', () => {
  const ico = readFileSync('static/favicon.ico');
  const HEADER_BYTES = 6;
  const ENTRY_BYTES = 16;

  it('is an icon container carrying several sizes, not one image renamed', () => {
    expect(ico.readUInt16LE(0)).toBe(0); // reserved
    expect(ico.readUInt16LE(2)).toBe(1); // 1 = icon, 2 would be a cursor
    expect(ico.readUInt16LE(4)).toBeGreaterThan(1);
  });

  it('points every directory entry at a payload that is inside the file', () => {
    // A packer that miscomputes one offset produces a file that opens in some readers
    // and not others, which is indistinguishable from "the browser cached the old one".
    const count = ico.readUInt16LE(4);
    for (let n = 0; n < count; n++) {
      const entry = HEADER_BYTES + ENTRY_BYTES * n;
      const size = ico.readUInt32LE(entry + 8);
      const offset = ico.readUInt32LE(entry + 12);
      expect(offset).toBeGreaterThanOrEqual(HEADER_BYTES + ENTRY_BYTES * count);
      expect(offset + size).toBeLessThanOrEqual(ico.length);
      expect(ico.readUInt8(entry)).toBeGreaterThan(0); // width, 0 would mean 256
    }
  });
});
