import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, Unique, Index } from 'typeorm';

/**
 * Stores the long-lived (static) MLS KeyPackage for each registered device.
 * A KeyPackage is an MLS credential bundle (public key + ciphersuite + extensions)
 * that other clients consume when adding this device to a group. There is at most
 * one active entry per (userId, deviceId) pair - uploading a new package replaces
 * the previous one. When the one-time key pool (OneTimeKeyPackage) is exhausted,
 * this fallback entry is used instead.
 */
@Entity()
@Unique(['userId', 'deviceId'])
export class KeyPackage {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /** Owner of the device this key package belongs to. */
  @Index()
  @Column({ type: 'varchar', length: 255 })
  userId: string;

  /** Opaque device identifier generated by the client at first launch. */
  @Column()
  deviceId: string;

  /** Base64-encoded serialised MLS KeyPackage used by peers to add this device to a group. */
  @Column()
  keyPackage: string; // Base64 encoded

  /** Human-readable device label (e.g. "Pixel 8 Pro"), stored for the device list UI. */
  @Column({ type: 'varchar', length: 80, nullable: true })
  deviceName?: string | null;

  /** Operating system identifier in lowercase (e.g. "android", "ios"), max 32 chars. */
  @Column({ type: 'varchar', length: 32, nullable: true })
  deviceOs?: string | null;

  /** Application semver string reported at registration (e.g. "1.4.2"), max 32 chars. */
  @Column({ type: 'varchar', length: 32, nullable: true })
  deviceAppVersion?: string | null;

  @CreateDateColumn()
  createdAt: Date;
}
