import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, Unique, Index } from 'typeorm';

/**
 * Stores the long-lived (static) MLS KeyPackage for each registered device.
 * A KeyPackage is an MLS credential bundle (public key + ciphersuite + extensions)
 * that other clients consume when adding this device to a group. There is at most
 * one active entry per (userId, deviceId) pair - uploading a new package replaces
 * the previous one. When the one-time key pool (OneTimeKeyPackage) is exhausted,
 * this fallback entry is used instead.
 */
@Entity()
@Unique(['userId', 'deviceId'])
export class KeyPackage {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /** Owner of the device this key package belongs to. */
  @Index()
  @Column({ type: 'varchar', length: 255 })
  userId: string;

  /** Opaque device identifier generated by the client at first launch. */
  @Column()
  deviceId: string;

  /** Base64-encoded serialised MLS KeyPackage used by peers to add this device to a group. */
  @Column()
  keyPackage: string; // Base64 encoded

  /** Human-readable device label (e.g. "Pixel 8 Pro"), stored for the device list UI. */
  @Column({ type: 'varchar', length: 80, nullable: true })
  deviceName?: string | null;

  /** Operating system identifier in lowercase (e.g. "android", "ios"), max 32 chars. */
  @Column({ type: 'varchar', length: 32, nullable: true })
  deviceOs?: string | null;

  /** Application semver string reported at registration (e.g. "1.4.2"), max 32 chars. */
  @Column({ type: 'varchar', length: 32, nullable: true })
  deviceAppVersion?: string | null;

  @CreateDateColumn()
  createdAt: Date;

  /**
   * When this package stops being usable, from its own MLS `Lifetime`, reported by the client that
   * minted it. `null` means no client has said yet.
   *
   * **AND IT CANNOT BE DERIVED FROM `createdAt` HERE, UNLIKE THE ONE-TIME POOL.** This row is
   * UPDATED in place on every re-registration and `registerDevice` resets `createdAt` deliberately
   * - a device re-enrolling after 30 days would otherwise fall off the device list's cutoff - while
   * the client REPUBLISHES the last-resort package it already holds rather than minting a new one.
   * So this row can carry today's date and a package that elapses in four days, and migration 024
   * leaves it NULL rather than backfilling a number that would certify an expired package as valid.
   *
   * A NULL reads as "not known to be expired": no device is locked out by a fact nobody has. What it
   * costs is that the aged last-resort packages counted on production on 2026-09-16 - 4 of them, 2
   * with a join stuck on them right now - stay invisible until their owners next connect.
   */
  @Column({ type: 'timestamptz', nullable: true })
  notAfter?: Date | null;
}
