/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmmlsclient_free: (a: number, b: number) => void;
export const decrypt_with_pin: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const encrypt_mls_state_blob: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const encrypt_with_pin: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const init_logger: () => void;
export const wasmmlsclient_add_member: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const wasmmlsclient_add_members_bulk: (a: number, b: number, c: number, d: any) => [number, number, number];
export const wasmmlsclient_clear_pending_commit: (a: number, b: number, c: number) => [number, number];
export const wasmmlsclient_create_group: (a: number, b: number, c: number) => [number, number];
export const wasmmlsclient_drop_group: (a: number, b: number, c: number) => void;
export const wasmmlsclient_export_secret: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
export const wasmmlsclient_force_create_group: (a: number, b: number, c: number) => [number, number];
export const wasmmlsclient_forget_group: (a: number, b: number, c: number, d: number) => void;
export const wasmmlsclient_generate_key_package: (a: number) => [number, number, number, number];
export const wasmmlsclient_generate_key_packages: (a: number, b: number) => [number, number, number];
export const wasmmlsclient_get_epoch: (a: number, b: number, c: number) => [number, number, number];
export const wasmmlsclient_get_groups: (a: number) => any;
export const wasmmlsclient_key_package_has_private: (a: number, b: number, c: number) => [number, number, number];
export const wasmmlsclient_merge_pending_commit: (a: number, b: number, c: number) => [number, number];
export const wasmmlsclient_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number];
export const wasmmlsclient_process_incoming_message: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const wasmmlsclient_process_incoming_message_bytes: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const wasmmlsclient_process_incoming_messages_batch: (a: number, b: number, c: number, d: any) => any;
export const wasmmlsclient_process_welcome: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const wasmmlsclient_remove_members: (a: number, b: number, c: number, d: any) => [number, number, number, number];
export const wasmmlsclient_remove_members_by_device: (a: number, b: number, c: number, d: any) => [number, number, number, number];
export const wasmmlsclient_save_state: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmmlsclient_send_message: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const wasmmlsclient_send_message_bytes: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
